"""create initial risk operations schema

Revision ID: 8afdf1919ddf
<<<<<<< HEAD
Revises:
=======
Revises: 
>>>>>>> 58e2af2715e314de060b741992c07c170726891e
Create Date: 2026-09-01 20:37:03.535174
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afdf1919ddf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor_type', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_audit_events_event_id')
    )
    op.create_index('ix_audit_correlation', 'audit_events', ['correlation_id'], unique=False)
    op.create_index('ix_audit_entity_occurred', 'audit_events', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_request', 'audit_events', ['request_id'], unique=False)
    op.create_index('ix_audit_type_occurred', 'audit_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('merchants',
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='merchantstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_external_id'), 'merchants', ['external_id'], unique=True)
    op.create_table('model_versions',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'RETIRED', name='versionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('model_type', sa.String(length=80), nullable=False),
    sa.Column('artifact_uri', sa.String(length=500), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=False),
    sa.Column('feature_schema_hash', sa.String(length=64), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_data_version', sa.String(length=64), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=True)
    op.create_table('policy_versions',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'RETIRED', name='versionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ml_weight', sa.Float(), nullable=False),
    sa.Column('graph_weight', sa.Float(), nullable=False),
    sa.Column('rule_weight', sa.Float(), nullable=False),
    sa.Column('approve_max', sa.Float(), nullable=False),
    sa.Column('manual_review_min', sa.Float(), nullable=False),
    sa.Column('cost_config_json', sa.JSON(), nullable=False),
    sa.Column('review_capacity', sa.Integer(), nullable=False),
    sa.Column('selection_data_version', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('approve_max < manual_review_min', name='ck_policy_threshold_order'),
    sa.CheckConstraint('graph_weight >= 0 AND graph_weight <= 1', name='ck_policy_graph_weight'),
    sa.CheckConstraint('ml_weight >= 0 AND ml_weight <= 1', name='ck_policy_ml_weight'),
    sa.CheckConstraint('review_capacity >= 0', name='ck_policy_capacity_nonnegative'),
    sa.CheckConstraint('rule_weight >= 0 AND rule_weight <= 1', name='ck_policy_rule_weight'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_versions_version'), 'policy_versions', ['version'], unique=True)
    op.create_table('customers',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('account_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'external_id', name='uq_customers_merchant_external')
    )
    op.create_index('ix_customers_merchant_account_created', 'customers', ['merchant_id', 'account_created_at'], unique=False)
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_table('identity_links',
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('identity_type', sa.Enum('DEVICE', 'PAYMENT', 'ADDRESS', 'PHONE', 'IP', name='identitytype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('observation_count >= 1', name='ck_identity_observations_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'identity_type', 'token_hash', name='uq_identity_link')
    )
    op.create_index('ix_identity_customer_last_seen', 'identity_links', ['customer_id', 'last_seen_at'], unique=False)
    op.create_index(op.f('ix_identity_links_customer_id'), 'identity_links', ['customer_id'], unique=False)
    op.create_index(op.f('ix_identity_links_merchant_id'), 'identity_links', ['merchant_id'], unique=False)
    op.create_index('ix_identity_type_token', 'identity_links', ['identity_type', 'token_hash'], unique=False)
    op.create_table('orders',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_value_paise', sa.Integer(), nullable=False),
    sa.Column('product_category', sa.String(length=80), nullable=False),
    sa.Column('discount_basis_points', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('discount_basis_points >= 0 AND discount_basis_points <= 10000', name='ck_orders_discount_range'),
    sa.CheckConstraint('order_value_paise >= 0', name='ck_orders_value_nonnegative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'external_id', name='uq_orders_merchant_external')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index('ix_orders_customer_ordered', 'orders', ['customer_id', 'ordered_at'], unique=False)
    op.create_index(op.f('ix_orders_merchant_id'), 'orders', ['merchant_id'], unique=False)
    op.create_index('ix_orders_merchant_ordered', 'orders', ['merchant_id', 'ordered_at'], unique=False)
    op.create_table('return_requests',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('requested_amount_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'SCORED', name='returnstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('payload_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('requested_amount_paise >= 0', name='ck_returns_amount_nonnegative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'external_id', name='uq_returns_merchant_external'),
    sa.UniqueConstraint('merchant_id', 'idempotency_key', name='uq_returns_merchant_idempotency')
    )
    op.create_index(op.f('ix_return_requests_customer_id'), 'return_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_return_requests_merchant_id'), 'return_requests', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_return_requests_order_id'), 'return_requests', ['order_id'], unique=False)
    op.create_index('ix_returns_customer_event', 'return_requests', ['customer_id', 'event_time'], unique=False)
    op.create_index('ix_returns_merchant_event', 'return_requests', ['merchant_id', 'event_time'], unique=False)
    op.create_index('ix_returns_status_event', 'return_requests', ['status', 'event_time'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('return_request_id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('policy_version_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('ml_probability', sa.Float(), nullable=False),
    sa.Column('graph_risk', sa.Float(), nullable=False),
    sa.Column('rule_risk', sa.Float(), nullable=False),
    sa.Column('final_risk', sa.Float(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'VERIFY', 'MANUAL_REVIEW', name='riskdecision', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=False),
    sa.Column('evidence_snapshot', sa.JSON(), nullable=False),
    sa.Column('explanation_source', sa.String(length=40), nullable=False),
    sa.Column('explanation_status', sa.String(length=40), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('final_risk >= 0 AND final_risk <= 1', name='ck_assessment_final_range'),
    sa.CheckConstraint('graph_risk >= 0 AND graph_risk <= 1', name='ck_assessment_graph_range'),
    sa.CheckConstraint('ml_probability >= 0 AND ml_probability <= 1', name='ck_assessment_ml_range'),
    sa.CheckConstraint('rule_risk >= 0 AND rule_risk <= 1', name='ck_assessment_rule_range'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessments_decision_scored', 'risk_assessments', ['decision', 'scored_at'], unique=False)
    op.create_index('ix_assessments_final_risk', 'risk_assessments', ['final_risk'], unique=False)
    op.create_index(op.f('ix_risk_assessments_assessment_id'), 'risk_assessments', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_risk_assessments_correlation_id'), 'risk_assessments', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_request_id'), 'risk_assessments', ['request_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_return_request_id'), 'risk_assessments', ['return_request_id'], unique=False)
    op.create_table('cases',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('risk_assessment_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'APPROVED', 'DISMISSED', 'ESCALATED', name='casestatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_assessment_id', name='uq_cases_assessment')
    )
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_cases_merchant_id'), 'cases', ['merchant_id'], unique=False)
    op.create_index('ix_cases_merchant_status_priority_opened', 'cases', ['merchant_id', 'status', 'priority', 'opened_at'], unique=False)
    op.create_table('analyst_decisions',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.Enum('APPROVE_CASE', 'DISMISS_CASE', 'ESCALATE_CASE', name='analystaction', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('checklist_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_decisions_actor_id'), 'analyst_decisions', ['actor_id'], unique=False)
    op.create_index('ix_analyst_decisions_case_created', 'analyst_decisions', ['case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analyst_decisions_case_id'), 'analyst_decisions', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyst_decisions_case_id'), table_name='analyst_decisions')
    op.drop_index('ix_analyst_decisions_case_created', table_name='analyst_decisions')
    op.drop_index(op.f('ix_analyst_decisions_actor_id'), table_name='analyst_decisions')
    op.drop_table('analyst_decisions')
    op.drop_index('ix_cases_merchant_status_priority_opened', table_name='cases')
    op.drop_index(op.f('ix_cases_merchant_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_risk_assessments_return_request_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_request_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_correlation_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_assessment_id'), table_name='risk_assessments')
    op.drop_index('ix_assessments_final_risk', table_name='risk_assessments')
    op.drop_index('ix_assessments_decision_scored', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('ix_returns_status_event', table_name='return_requests')
    op.drop_index('ix_returns_merchant_event', table_name='return_requests')
    op.drop_index('ix_returns_customer_event', table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_order_id'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_merchant_id'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_customer_id'), table_name='return_requests')
    op.drop_table('return_requests')
    op.drop_index('ix_orders_merchant_ordered', table_name='orders')
    op.drop_index(op.f('ix_orders_merchant_id'), table_name='orders')
    op.drop_index('ix_orders_customer_ordered', table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_identity_type_token', table_name='identity_links')
    op.drop_index(op.f('ix_identity_links_merchant_id'), table_name='identity_links')
    op.drop_index(op.f('ix_identity_links_customer_id'), table_name='identity_links')
    op.drop_index('ix_identity_customer_last_seen', table_name='identity_links')
    op.drop_table('identity_links')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_index('ix_customers_merchant_account_created', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_policy_versions_version'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_merchants_external_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index('ix_audit_type_occurred', table_name='audit_events')
    op.drop_index('ix_audit_request', table_name='audit_events')
    op.drop_index('ix_audit_entity_occurred', table_name='audit_events')
    op.drop_index('ix_audit_correlation', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
