import {useEffect,useRef}from"react";import{Link,Route,Routes,useNavigate,useParams}from"react-router-dom";import{useMutation,useQuery,useQueryClient}from"@tanstack/react-query";import cytoscape from"cytoscape";import{api,ApiError,Case}from"./api";import{BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer}from"recharts";
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n/100); const when=(s:string)=>new Date(s).toLocaleString();
function Badge({value}:{value:string}){return <span className={`badge ${value.toLowerCase()}`}>{value.replaceAll("_"," ")}</span>}
function Shell({children}:{children:React.ReactNode}){return <div className="shell"><aside><h1>Razor<span>Shield</span></h1><p className="demo">DEMO MODE • HUMAN REVIEW REQUIRED</p>{[["/","Overview"],["/cases","Case queue"],["/performance","Model performance"]].map(([to,n])=><Link to={to} key={to}>{n}</Link>)}</aside><main>{children}</main></div>}
function Failure({error}:{error:unknown}){const e=error as ApiError;return <div className="failure"><h2>Service unavailable</h2><p>{e.message}. Check the local backend and retry.</p>{e.requestId&&<code>Request ID: {e.requestId}</code>}</div>}
function Overview(){const r=useQuery({queryKey:["ready"],queryFn:api.ready,retry:2});const c=useQuery({queryKey:["cases"],queryFn:()=>api.cases()});const b=useQuery({queryKey:["business"],queryFn:api.business});if(r.error)return <Failure error={r.error}/>;const cases=c.data?.items??[];const business=b.data?.business??{};return <><header><div><p className="eyebrow">RISK OPERATIONS</p><h2>Coordinated return abuse, made visible.</h2></div><Badge value={r.data?.status??"LOADING"}/></header><div className="cards"><Card n="Open cases" v={String(c.data?.total??"—")}/><Card n="Net estimated savings" v={business.net_estimated_savings_paise?money(business.net_estimated_savings_paise):"—"}/><Card n="Prevented loss" v={business.estimated_prevented_loss_paise?money(business.estimated_prevented_loss_paise):"—"}/><Card n="Model" v={r.data?.model??"loading"}/></div><section><h3>Priority queue</h3><CaseTable cases={cases}/></section><p className="notice">Synthetic held-out performance demonstrates the evaluation pipeline and is not a claim of production accuracy.</p></>}
function Card({n,v}:{n:string;v:string}){return <div className="card"><p>{n}</p><strong>{v}</strong></div>}
function CaseTable({cases}:{cases:Case[]}){return <div className="table">{cases.length?cases.map(c=><Link className="row" to={`/cases/${c.case_id}`} key={c.case_id}><span>{c.case_id.slice(0,8)}</span><Badge value={c.status}/><span>Priority {c.priority}</span><time>{when(c.opened_at)}</time></Link>):<p className="empty">No cases match this view.</p>}</div>}
function Queue(){const q=useQuery({queryKey:["cases"],queryFn:()=>api.cases()});if(q.error)return <Failure error={q.error}/>;return <><header><div><p className="eyebrow">CASE QUEUE</p><h2>Review with evidence, never automatic rejection.</h2></div></header><section><CaseTable cases={q.data?.items??[]}/></section></>}
function Graph({id}:{id:string}){const host=useRef<HTMLDivElement>(null);const q=useQuery({queryKey:["graph",id],queryFn:()=>api.graph(id)});useEffect(()=>{if(host.current&&q.data?.nodes?.length){const cy=cytoscape({container:host.current,elements:q.data,style:[{selector:"node",style:{"background-color":"#3b82f6",label:"data(id)",color:"#dbeafe"}},{selector:"edge",style:{width:2,"line-color":"#64748b"}}],layout:{name:"cose"}});return()=>cy.destroy()}},[q.data]);return <div><h3>Connected identity graph</h3>{q.data?.nodes?.length>1?<div className="graph" ref={host}/>:<p className="empty">No linked identities are safely available for this case.</p>}</div>}
function Detail(){const{id=""}=useParams();const qc=useQueryClient();const q=useQuery({queryKey:["case",id],queryFn:()=>api.case(id)});const a=useQuery({queryKey:["audit",id],queryFn:()=>api.audit(id)});const action=useMutation({mutationFn:(x:string)=>api.decision(id,x),onSuccess:()=>qc.invalidateQueries({queryKey:["case",id]})});if(q.error)return <Failure error={q.error}/>;if(!q.data)return <p>Loading case…</p>;const x=q.data.assessment;return <><Link to="/cases">← Case queue</Link><header><div><p className="eyebrow">CASE DETAIL</p><h2>Risk {Math.round(x.final_risk*100)}%</h2></div><Badge value={x.decision}/></header><div className="cards"><Card n="ML probability" v={`${Math.round(x.ml_probability*100)}%`}/><Card n="Graph risk" v={`${Math.round(x.graph_risk*100)}%`}/><Card n="Rule risk" v={`${Math.round(x.rule_risk*100)}%`}/></div><section><h3>Defensive evidence</h3>{(x.evidence.rules??[]).map((e:any)=><p key={e.rule_id}>• {e.evidence}</p>)||<p className="empty">No rules triggered.</p>}<p className="notice">A human analyst must review before any adverse action.</p><div className="actions">{["APPROVE_CASE","DISMISS_CASE","ESCALATE_CASE"].map(z=><button key={z} onClick={()=>action.mutate(z)} disabled={action.isPending}>{z.replace("_CASE","").replaceAll("_"," ")}</button>)}</div></section><Graph id={id}/><section><h3>Audit timeline</h3>{a.data?.items?.map((e:any)=><p key={e.occurred_at}>{when(e.occurred_at)} — {e.event_type}</p>)}</section></>}
function Performance(){const q=useQuery({queryKey:["model"],queryFn:api.model});if(q.error)return <Failure error={q.error}/>;const m=q.data?.evaluation?.test_metrics;if(!m)return <p>Loading locked evaluation…</p>;const data=Object.entries(m.decision_rates||{}).map(([name,value])=>({name,value:Math.round(Number(value)*100)}));return <><header><div><p className="eyebrow">LOCKED EVALUATION</p><h2>Model performance</h2></div></header><div className="cards">{[["Precision",m.precision],["Recall",m.recall],["F1",m.f1],["PR-AUC",m.pr_auc],["ROC-AUC",m.roc_auc],["Brier",m.brier_score]].map(([n,v])=><Card key={String(n)} n={String(n)} v={`${(Number(v)*100).toFixed(1)}%`}/>)}</div><section><h3>Decision distribution</h3><div className="chart"><ResponsiveContainer><BarChart data={data}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="value" fill="#3b82f6"/></BarChart></ResponsiveContainer></div><p>18.4% precision is approximately 2.35× lift over 7.83% prevalence; it does not establish production accuracy.</p><p className="notice">Synthetic held-out performance demonstrates the evaluation pipeline and is not a claim of production accuracy.</p></section></>}
export default function App(){return <Shell><Routes><Route path="/" element={<Overview/>}/><Route path="/cases" element={<Queue/>}/><Route path="/cases/:id" element={<Detail/>}/><Route path="/performance" element={<Performance/>}/></Routes></Shell>}
